version: '3.7'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ${PWD}/../..:/billrun:ro
            - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - "php"
            - "mongodb"
        environment:
        - "APPLICATION_ENV=container"    
    php:
        build: 
            context: ./billrun-php7
            dockerfile: Dockerfile
        image: billrun-php71
        container_name: billrun
        restart: always
        environment:
        - "APPLICATION_ENV=container"
        - "XDEBUG_CONFIG=remote_host=10.103.0.1 remote_port=9090 remote_enable=1 xdebug.idekey=${XDEBUG_CONFIG:-netbeans-xdebug}"
        - "BR_MDB_HOST=billrun-mongodb:27017"
        - "BR_MDB_DBNAME=billing_container"
        volumes:
            - ${PWD}/../..:/billrun
    mongodb:
        image: mongo:3.6
        container_name: billrun-mongo
        restart: always
        volumes:
            - ${PWD}/../..:/billrun:ro
            # - ${PWD}/../persist/data/db/mongo-3.6:/data/db
            # - ${PWD}/../persist/backup:/backup
            - ${PWD}/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        ports:
            - 27018:27017

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.0/16