version: '3.7'

services:
    web:
        image: nginx:latest
        container_name: billrun-nginx
        ports:
            - "8074:80"
        restart: always
        volumes:
            - ./../..:/billrun:ro
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - "php"
            - "mongodb"
        environment:
        - "APPLICATION_ENV=container"    
    php:
        build: 
            context: ./billrun-php74
            dockerfile: Dockerfile
        image: billrun-php74
        container_name: billrun-app
        privileged: true
        restart: always
        environment:
        - "APPLICATION_ENV=container"
        - "XDEBUG_CONFIG=client_host=10.103.0.1 client_port=9090 mode=develop"
        - "BR_MDB_HOST=billrun-mongodb:27017"
        - "BR_MDB_DBNAME=billing_container"
        volumes:
            - ./../..:/billrun
        command: sh -c "composer update && php-fpm "
    mongodb:
        image: mongo:3.6
        container_name: billrun-mongodb
        restart: always
        volumes:
            - ./../..:/billrun:ro
            - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        ports:
            - 27017:27017
    chrome:
        image: selenium/standalone-chrome
        container_name: billrun-standalone-chrome
        restart: always

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16
